services:
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules  # Avoid overwriting node_modules in container
    working_dir: /usr/src/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    command: ["nodemon", "src/server.js"]

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
