services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules  # Avoid overwriting node_modules in container
    working_dir: /usr/src/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
      - redis
    command: ["nodemon", "src/server.js"]

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
